### ISSUE TITLE
Rebuild server

### ISSUE THREAD

**Issue by Tomohiro** [Tomohiro/Documents#34]
### Stack

- Digital Ocean
- CoreOS
- Docker
- fleet
- etcd
- IRC Gatewayas
    - TweetIRCGateway to atig
    - lig
     - iig
     - hackway
     - 2nd_gig
     - fig (not works currently...)

**Comment by Tomohiro** [comment]
I'm working on https://github.com/Tomohiro/dockerfiles.

**Comment by Tomohiro** [comment]
CoreOS 上で SSH のポートを替える場合の問題点。
公式ドキュメントどおり，`sshd.socket` を作る。
https://coreos.com/docs/cluster-management/setup/customizing-sshd/#changing-the-sshd-port 

しかし，`sshd.socket` よりも先に `sshd.service` が起動する場合，ポートが衝突して，`sshd.socket` が起動しなくなるケースがあるので，`cloud-config` に以下のように書き込む

```yaml
  units:
    - name: sshd.service
      command: stop
    - name: sshd.socket
      command: start
      content: |
        [Socket]
        ListenStream=22
        Accept=yes
```

`sshd.service` を停止した後で `sshd.socket` を起動するように変更するとうまくいく
